### ISSUE TITLE
Adding gradient boosting and catboost algorithm examples in README.md

### ISSUE THREAD

**Issue by Satyajeet-code** [pawarashish564/mlutil#2]

**Comment by pawarashish564** [comment]
Good Issue. We'll consider this type of model. If you have any material from Kaggle or Jovian please do consider sharing.

**Comment by Satyajeet-code** [comment]
Hey,

Actually, I wanted to add these 2 algorithms and make a pr. I also reached
out to you on discord.

**Comment by pawarashish564** [comment]
Oh my bad. I was logged off from the discord. Do your work make a PR.

**Comment by Satyajeet-code** [comment]
Yeah I did it already, also made a pr. Please check.

**Comment by pawarashish564** [comment]
I checked your PR It just added examples in README only.  If you have any catboost or gradient descent algorithm workflow or something then add it. four examples sufficient to explain workflow of **hyp_pipeline** method.
