### ISSUE TITLE
Information regarding getting started

### ISSUE THREAD

**Issue by Astha-Bhushan** [pawarashish564/mlutil#3]
so basically what i have to do? I have to design a model using mlutil .

**Comment by pawarashish564** [comment]
No, you don't have to define the model. mlutil is a collection of Machine Learning snippets. So If you have any python code that you frequently use in any Machine Learning Project, Add that code in mlutil.py file. 
For example,
* Long Code that is frequently used such as data viz, data cleaning
* Any Model workflow such as Neural Nets or Pytorch
